### ISSUE TITLE
Add checks for the existence of jdk/sdk directories

### ISSUE THREAD

**Issue by AnthonyNSK** [icerockdev/moko-doctor#3]
When configuring JAVA_HOME, ANDROID_SDK_ROOT encountered a problem:
the script doesn't say that the specified directories don't exist. 
I suggest going to doctor.sh add checks that the specified directories exist and somehow display this in the output.

**Comment by kramlex** [comment]
added checking for the existence of directories specified in the JAVA_HOME and ANDROID_SDK_ROOT variables

<img width="874" alt="Снимок экрана 2021-09-03 в 15 40 13" src="https://user-images.githubusercontent.com/43269086/131976899-7378aead-2d8a-45fa-bfc1-6327a17f3dc8.png">
